@api = http://localhost:4000

POST {{api}}/Enfermedad/createEnfermedades
Content-Type: application/json

[
    {
        "nombre": "Osteogénesis imperfecta",
        "descripcion": "Conjunto de transtornos hereditarios caracterizados por huesos frágiles que se fracturan fácilmente.",
        "sintomas": [["Anomalías ósea", "0.15"],["Dientes frágiles", "0.12"],["Estatura baja", "0.13"],["Cara de forma triangular", "0.10"], ["Pérdidas auditivas en la edad adulta", "0.6"], ["Articulaciones laxas", "0.4"]],
        "causas": "A menudo es causada por un defecto en un gen que produce el colágeno tipo 1.",
        "recomendaciones": "Evitar aquellas actividades que supongan un riesgo de caída o de choque o que ejerzan demasiado estrés sobre los huesos.",
        "consideraciones": "El tratamiento puede ayudar pero no tiene cura."
    },
    {
        "nombre": "COVID‑19",
        "descripcion": "Enfermedad respiratoria muy contagiosa causada por el virus SARS-CoV-2.",
        "sintomas": ["Fiebre","Tos","Cansancio","Pérdida del gusto","Pérdida del olfato","Dolor de garganta","Dolor de cabeza","Diarrea"],
        "causas": "Cuando alguien contagiado con COVID-19 exhala o tose, expulsa pequeñas gotas que contienen el virus. Estas gotas pueden entrar en la boca o la nariz de alguien sin el virus, causando así una infección.",
        "recomendaciones": "Lo recomendable es que las personas que sufran síntomas leves y tengan un buen estado de salud general se confinen en casa.",
        "consideraciones": "La vacunación está ayudando a reducir los casos de muerte por esta enfermedad."
    },
    {
        "nombre": "Osteoporosis",
        "descripcion": "Enfermedad esquelética en la que se produce una disminución de la densidad de masa ósea.",
        "sintomas": ["Dolor de espalda","Pérdida de estatura con el tiempo","Postura encorvada","Dolor de cintura"],
        "causas": "A menudo es causada por un defecto en un gen que produce el colágeno tipo 1.",
        "recomendaciones": "Mantener una alimentación saludable, variada y equilibrada, y realizar ejercicios regularmente.",
        "consideraciones": "Las fracturas por osteoporosis ocurren con mayor frecuencia en la cadera, la muñeca o la columna vertebral."
    },
    {
        "nombre": "Bronquitis",
        "descripcion": "Es una inflamación del revestimiento de los bronquios que llevan el aire hacia adentro y fuera de los pulmones.",
        "sintomas": ["Dolor en el pecho","Dolores corporales leves","Dolor de garganta","Tos con mucosidad","Dolor de cabeza leve","Dolores corporales leves","Dificultad para respirar"],
        "causas": "Suele ser provocada por un virus y, con frecuencia, ocurre después de una infección de las vías respiratorias superiores.",
        "recomendaciones": "Se recomienda evitar el humo del cigarrillo, lavarse bien las manos y vaunarse.",
        "consideraciones": "Se recomienda"
    },
    {
        "nombre": " Cólera",
        "descripcion": "Es una enfermedad diarreica aguda causada por la ingestión de alimentos o agua contaminados con el bacilo Vibrio cholerae.",
        "sintomas": ["Deshidratación","Diarrea","Náuseas","Vómitos","Dolor de cabeza leve","Dolores corporales leves","Dificultad para respirar"],
        "causas": "La bacteria que causa la infección por cólera se denomina Vibrio cholerae",
        "recomendaciones": "Se recomienda evitar el humo del cigarrillo, lavarse bien las manos y vaunarse.",
        "consideraciones": "Se recomienda"   
    }
]