@api = http://localhost:4000

POST {{api}}/Enfermedad/createEnfermedades
Content-Type: application/json

[
    {
        "nombre": "Osteogénesis imperfecta",
        "descripcion": "Conjunto de transtornos hereditarios caracterizados por huesos frágiles que se fracturan fácilmente.",
        "sintomas": [["Anomalías óseas", 0.15],["Dientes frágiles", 0.13],["Estatura baja", 0.12],["Cara de forma triangular", 0.10], ["Pérdidas auditivas en la edad adulta", 0.06], ["Articulaciones laxas", 0.04]],
        "causas": "A menudo es causada por un defecto en un gen que produce el colágeno tipo 1.",
        "recomendaciones": "Evitar aquellas actividades que supongan un riesgo de caída o de choque o que ejerzan demasiado estrés sobre los huesos.",
        "consideraciones": "El tratamiento puede ayudar pero no tiene cura."
    },
    {
        "nombre": "COVID‑19",
        "descripcion": "Enfermedad respiratoria muy contagiosa causada por el virus SARS-CoV-2.",
        "sintomas": [["Fiebre", 0.15],["Tos",0.13],["Cansancio",0.12],["Pérdida del gusto",0.11],["Pérdida del olfato",0.09],["Dolor de garganta",0.05],["Dolor de cabeza",0.03],["Diarrea",0.02]],
        "causas": "Cuando alguien contagiado con COVID-19 exhala o tose, expulsa pequeñas gotas que contienen el virus. Estas gotas pueden entrar en la boca o la nariz de alguien sin el virus, causando así una infección.",
        "recomendaciones": "Mantener una distancia de seguridad con otras personas (de 1 metro como mínimo), utilizar mascarilla en público, prioriza los espacios abiertos y con buena ventilación en lugar de los espacios cerrados.",
        "consideraciones": "La vacunación está ayudando a reducir los casos de muerte por esta enfermedad."
    },
    {
        "nombre": "Osteoporosis",
        "descripcion": "Enfermedad esquelética en la que se produce una disminución de la densidad de masa ósea.",
        "sintomas": [["Dolor de espalda",0.15],["Pérdida de estatura con el tiempo",0.13],["Postura encorvada",0.12],["Dolor de cintura",0.11]],
        "causas": "A menudo es causada por un defecto en un gen que produce el colágeno tipo 1.",
        "recomendaciones": "Mantener una alimentación saludable, variada y equilibrada, y realizar ejercicios regularmente.",
        "consideraciones": "Las fracturas por osteoporosis ocurren con mayor frecuencia en la cadera, la muñeca o la columna vertebral."
    },
    {
        "nombre": "Bronquitis aguda",
        "descripcion": "Es una inflamación del revestimiento de los bronquios que llevan el aire hacia adentro y fuera de los pulmones.",
        "sintomas": [["Dolor en el pecho",0.14],["Dolores corporales leves",0.13],["Dolor de garganta",0.13],["Tos con mucosidad",0.10],["Dolor de cabeza leve",0.08],["Dolores corporales leves",0.06],["Dificultad para respirar",0.06]],
        "causas": "Suele ser provocada por un virus y, con frecuencia, ocurre después de una infección de las vías respiratorias superiores.",
        "recomendaciones": "Se recomienda evitar el humo del cigarrillo, lavarse bien las manos y vaunarse.",
        "consideraciones": "..."
    },
    {
        "nombre": "Cólera",
        "descripcion": "Es una enfermedad diarreica aguda causada por la ingestión de alimentos o agua contaminados con el bacilo Vibrio cholerae.",
        "sintomas": [["Deshidratación",0.16],["Diarrea",0.12],["Náuseas",0.12],["Vómitos",0.10],["Dolor de cabeza leve",0.05],["Dolores corporales leves",0.03],["Dificultad para respirar",0.02]],
        "causas": "La bacteria que causa la infección por cólera se denomina Vibrio cholerae",
        "recomendaciones": "Se recomienda evitar el humo del cigarrillo, lavarse bien las manos y vaunarse.",
        "consideraciones": "..."   
    },
    {
        "nombre": "Viruela símica",
        "descripcion": "Se trata de una enfermedad zoonótica viral, lo que significa que puede transmitirse de animales a humanos.",
        "sintomas": [["Fiebre",0.13],["Inflamación de los ganglios linfáticos",0.12],["Dolor de cabeza",0.10],["Escalofríos",0.09],["Dolores musculares",0.07],["Dolores de la espalda",0.09],["Agotamiento",0.06],["Sarpullido ",0.04]],
        "causas": "No se sabe donde se origina la viruela del simio, pero se cree que se transmite a través de pequeños roedores y ardillas de las selvas tropicales de África, principalmente en África occidental y central.",
        "recomendaciones": "Se recomienda abstenerse de tener contacto cercano con terceros, evitar asistir a reuniones y seguir los consejos emitidos por las autoridades sanitarias correspondientes",
        "consideraciones": "..."
    },
    {
        "nombre": "Viruela Kawasaki",
        "descripcion": "La enfermedad de Kawasaki es una vasculitis, es decir, una inflamación generalizada de los vasos sanguíneos, que tiende a afectar, sobre todo, a las arterias medianas de todo el organismo.",
        "sintomas": [["Fiebre",0.15],["Eritema",0.13],["Nódulos linfáticos inflamados",0.07],["Inyección conjuntival",0.09],["Garganta inflada",0.04],["Lengua inflamada",0.04],["Dolor abdominal",0.02],["Dolores articulares",0.03]],
        "causas": "Se sospecha que podría existir un componente genético que predispone a desarrollar una reacción inmunológica exagerada después de la infección por un agente",
        "recomendaciones": "Se recomienda realizar tratamiento inmediato de la enfermedad de Kawasaki incompleta, la terapia con aspirina y la obtención de un ecocardiograma en caso de shock.",
        "consideraciones": "..."
    },
    {
        "nombre": "Sinusitis crónica",
        "descripcion": "La sinusitis crónica se produce cuando los espacios dentro de la nariz y la cabeza (senos paranasales) están hinchados e inflamados durante tres meses o más, a pesar del tratamiento.",
        "sintomas": [["Inflamación nasal",0.13],["Secreción espesa de la nariz",0.12],["Nariz tapada",0.11],["Secreción posnasal",0.10],["Hinchazón alrededor de los ojos",0.05],["Reducción del sentido del olfato",0.04],["Reducción del sentido del gusto",0.02],["Dolor de oído",0.01]],
        "causas": "infecciones, crecimientos en los senos paranasales (pólipos nasales) o hinchazón del revestimiento de los senos paranasales.",
        "recomendaciones": "Se recomienda evitar el contacto con personas resfriadas o con otras infecciones.",
        "consideraciones": "..."
    },
    {
        "nombre": "Infección urinaria",
        "descripcion": "Son infecciones comunes que ocurren cuando entran bacterias a la uretra, generalmente de la piel o el recto, e infectan las vías urinarias.",
        "sintomas": [["Ardor al orinar",0.12],["Orinar con frecuencia",0.10],["Sangre en la orina",0.09],["Escalofríos",0.02],["Fiebre",0.01]],
        "causas": "Las infecciones urinarias son causadas por bacterias",
        "recomendaciones": "Bebe mucha agua. El agua ayuda a diluir la orina y expulsar las bacterias. Evita las bebidas que puedan irritar la vejiga. Evita el café, el alcohol y los refrescos que contengan jugos de cítricos o cafeína hasta que la infección haya desaparecido.",
        "consideraciones": "Se tratan con antibióticos. Sin embargo, cada vez que usted toma antibióticos, estos pueden causar efectos secundarios, que incluyen sarpullido, mareos, náuseas, diarrea e infecciones por hongos."
    },
    {
        "nombre": "Influenza",
        "descripcion": "Es una enfermedad respiratoria contagiosa provocada por los virus de la influenza que infectan la nariz, la garganta y en algunos casos los pulmones.",
        "sintomas": [["Fiebre",0.13],["Tos",0.12],["Dolor de garganta",0.10],["Secreción nasal",0.06],["Dolores musculares",0.05],["Dolores de cabeza",0.04],["fatiga",0.02]],
        "causas": "Provocada por los virus de la influenza que infectan la nariz, la garganta y en algunos casos los pulmones.",
        "recomendaciones": "Se recomienda evitar el contacto cercano con personas que estén enfermas, evitar tocarse los ojos, la nariz o la boca, Practicar otros buenos hábitos de salud.",
        "consideraciones": "..."
    },
    {
        "nombre": "VIH/Sida",
        "descripcion": "Es una afección crónica que pone en riesgo la vida provocada por el virus de la inmunodeficiencia humana (VIH). Al dañar tu sistema inmunitario, el VIH interfiere con la capacidad de tu cuerpo para luchar contra infecciones y enfermedades.",
        "sintomas": [["Candidiasis",0.10],["Pérdida de peso",0.09],["Herpes ",0.12],["Neumonía",0.11],["Ganglios linfáticos inflamados",0.06],["Diarrea crónica",0.05],["Manchas blancas",0.12]],
        "causas": "Puede trasmitirse a través del contactomatrimonio sexual, la inyección de drogas ilícitas o el uso compartido de agujas, el contacto con sangre infectada.",
        "recomendaciones": "Se recomienda tener los cuidados respectivos durante el acto sexual",
        "consideraciones": "Actualmente no se cuenta con un tratamiento para curar esta infección, pero se ha logrado, mediante el cumplimiento de varias acciones de salud, encabezadas por el tratamiento antirretroviral, que los pacientes con VIH/sida vivan muchos años y con una buena calidad de vida"
    },
    {
        "nombre": "Sífilis",
        "descripcion": "La sífilis es una ETS que puede causar complicaciones a largo plazo o la muerte, si no se trata de manera adecuada.",
        "sintomas": [["Inflamación de las glándulas linfáticas", 0.15],["Dolor de garganta",0.03],["pérdida de cabello",0.04],["Pérdida de peso",0.07],["Fiebre",0.01],["Dolor de cabeza", 0.01],["Fatiga",0.02]],
        "causas": "La causa de la sífilis es una bacteria llamada Treponema pallidum. La vía más común de transmisión de la sífilis es a través del contacto con la llaga de una persona infectada durante la actividad sexual.",
        "recomendaciones": "Se recomienda hacerse pruebas regularmente y usar condón o barreras de látex bucales cuando tengas sexo",
        "consideraciones": "Los condones previenen la transmisión de la sífilis al evitar el contacto con las llagas, pero a veces, las llagas pueden estar en áreas que el condón no cubre. La sífilis todavía se puede transmitir al tener contacto con estas llagas."
    },
    {
        "nombre": "Gonorrea",
        "descripcion": "Es una enfermedad de transmisión sexual (ETS) que puede infectar tanto a los hombres como a las mujeres. Puede causar infecciones en los genitales, el recto y la garganta. Es una infección muy común, especialmente en las personas jóvenes de 15 a 24 años.",
        "sintomas": [["Ardor al orinar",0.13],["Secreción del pene",0.12],["Testículos sensibles",0.12],["Testículos inflamados",0.15],["Abertura del pene",0.15],["Dolor de garganta",0.04]],
        "causas": "Es causada por la bacteria Neisseria gonorrhoeae y la puede propagar cualquier tipo de actividad sexual. Se puede contraer por contacto con la boca, la garganta, los ojos, la uretra, la vagina, el pene o el ano.",
        "recomendaciones": "La gonorrea se previene con el uso del preservativo o condón en todas las relaciones sexuales",
        "consideraciones": "Para prevenir la transmisión durante el parto existe una norma que establece la aplicación de gotas antibióticas en los ojos a todos los recién nacidos."
    },
    {
        "nombre": "Chikunguña",
        "descripcion": "Es una enfermeda​d viral que se propaga por la picadura de los mosquitos Aedes aegypti o Aedes albopictus infectados, que son los mismos vectores del dengue.",
        "sintomas": [["Dolores articulares",0.16],["Fiebre",0.09],["Dolores musculares",0.07],["Dolores de cabeza",0.06],["Náuseas",0.04],["Erupciones cutáneas",0.05]],
        "causas": "La enfermedad se transmite por la picadura de los mosquitos hembra infectados Aede aegypti y Aedes albopictus (mosquito tigre). Son mosquitos hematófogos diurnos y permanecen infectantes hasta su muerte.",
        "recomendaciones": "Se recomienda el tratamiento inmediato de la enfermedad de Kawasaki incompleta, la terapia con aspirina y la obtención de un ecocardiograma en caso de shock.",
        "consideraciones": "No hay vacuna contra el virus del chikunguña. El tratamiento se c​oncentra en aliviar los síntomas."
    },
    {
        "nombre": "Faringitis",
        "descripcion": "La faringitis es una afección que cursa con irritación, inflamación o infección de la faringe, y muy particularmente de su tejido linfoide.",
        "sintomas": [["Malestar general",0.10],["Fiebre",0.09],["Dolor de garganta al tragar",0.15],["Enrojecimiento de la faringe",0.13],["Ganglios cervicales inflamados",0.10]],
        "causas": "La mayoría de las faringitis agudas son procesos infecciosos, debidos a virus o bacterias; los virus causan entre un 80% y un 90% de las faringitis tanto en niños como en los adultos.",
        "recomendaciones": "Beber líquidos suaves, evitar los ambientes muy contaminados, evitar los cambios bruscos de temperatura",
        "consideraciones": "..."
    },
    {
        "nombre": "Artrosis",
        "descripcion": "La osteoartritis o artrosis es la enfermedad degenerativa articular más frecuente, caracterizada por la destrucción del cartílago hialino que recubre las superficies óseas.",
        "sintomas": [["Pérdida de flexibilidad",0.10],["Osteofitos",0.08],["Dolor articular",0.12],["Deformidad articular",0.13],["Inflamación en las articulaciones",0.13]],
        "causas": "La osteoartritis se produce cuando el cartílago que amortigua los extremos de los huesos en las articulaciones se deteriora progresivamente.",
        "recomendaciones": "No se deben hacer aquellos ejercicios que produzcan dolor, cuidar posturas",
        "consideraciones": "..."
    },
    {
        "nombre": "Artritis",
        "descripcion": "La artritis es la hinchazón y la sensibilidad de una o más de las articulaciones.",
        "sintomas": [["Dolor articular",0.12],["Inflamación articular",0.10],["Enrojecimiento articular",0.10],["Disminución de la amplitud de movimiento",0.08],["Hinchazón en las articulaciones",0.09],["Rigidez",0.07]],
        "causas": "La artritis involucra la degradación de las estructuras articulares, particularmente del cartílago.",
        "recomendaciones": "Mantenga un peso corporal correcto. La obesidad es una de las causas de la enfermedad.",
        "consideraciones": "..."
    },
    {
        "nombre": "Hepatitis B",
        "descripcion": "Infección grave del hígado causada por el virus de la hepatitis B que se puede prevenir fácilmente mediante una vacuna.",
        "sintomas": [["Color amarillento de los ojos",0.20],["Dolor abdominal",0.07],["Orina oscura",0.10],["Fatiga",0.06],["Picazón",0.04],["Pérdida del apetito",0.08],["Color amarillento en la piel",0.20]],
        "causas": "Ascendencia con Hepatitis B o pincharse accidentalmente con una aguja que usó una persona infectada",
        "recomendaciones": "Vacunarse contra la hepatitis B",
        "consideraciones": "La artrosis es la enfermedad reumática más frecuente, especialmente entre personas de edad avanzada"
    },
    {
        "nombre": "Diabetes",
        "descripcion": "Un grupo de enfermedades que tiene como resultado un exceso de azúcar en la sangre (glucosa sanguínea elevada).",
        "sintomas": [["Aumento de la sed",0.11],["Fatiga",0.10],["Visión borrosa",0.13],["Pérdida de peso",0.09],["Aumento del apetito",0.09],["Micción frecuente",0.04],["Infecciones frecuentes",0.05]],
        "causas": "El páncreas no produce suficiente insulina, las células no responden de manera normal a la insulina",
        "recomendaciones": "Adaptar la alimentación, mantener una hidratación adecuada, practicar ejercicio de forma regular, realizar controles de glucosa con frecuencia y de forma estructurada",
        "consideraciones": "..."
    },
    {
        "nombre": "Insuficiencia Renal",
        "descripcion": "Afección que provoca que los riñones pierdan la capacidad de eliminar los desechos y equilibrar los fluidos.",
        "sintomas": [["Disminución del volumen de orina excretado",0.15],["Hinchazón en las piernas",0.12],["Hinchazón en los pies",0.10],["Falta de aire",0.09],["Fatiga",0.06],["Desorientación",0.03],["Náuseas",0.02],["Debilidad",0.02]],
        "causas": "Administración de algunos fármacos y de contrastes yodados. Tensión arterial muy baja u obstrucciones provocadas por posibles cálculos renales, algunos tumores o un agrandamiento de la próstata en varones. Diabetes o Hipertensión",
        "recomendaciones": "No fumar. Evitar el consumo de antiinflamatorios, sólo en ocasiones puntuales, siempre bajo prescripción médica. Controles periódicos del estado de salud (especialmente en analíticas de sangre y orina que recojan valores como la urea, la creatinina y la glucosa).",
        "consideraciones": "..."
    },
    {
        "nombre": "Elefantiasis",
        "descripcion": "Enfermedad parasitaria tropical que afecta los ganglios linfáticos y los vasos linfáticos.",
        "sintomas": [["Inflamación en las piernas",0.16],["Inflamación en los brazos",0.15],["Inflamación en los genitales",0.14],["Fiebre elevada",0.06],["Sensibilidad a la luz",0.05],["Pericarditis",0.03],["Comezón en el cuerpo",0.04]],
        "causas": "Se produce por la transmisión de unos parásitos denominados filarias a través de los mosquitos",
        "recomendaciones": "Evitar la picadura de los mosquitos, sobre todo con mosquiteras con impregnación de insecticidas, y el uso de repelentes en la piel y la ropa",
        "consideraciones": "..."
    },
    {
        "nombre": "Hepatitis A",
        "descripcion": "Infección hepática muy contagiosa ocasionada por el virus de la hepatitis A.",
        "sintomas": [["Fatiga",0.07],["Náuseas",0.08],["Dolor abdominal",0.10],["Pérdida del apetito",0.09],["Fiebre",0.06],["Color amarillento en la piel",0.20],["Orina de color oscuro",0.05],["Dolor articular",0.04]],
        "causas": "Comer alimentos manipulados por alguien con el virus que no se lavó bien las manos después de ir al baño. Estar en contacto cercano con una persona infectada",
        "recomendaciones": "Vacunarse contra la hepatitis A. Lavarse las manos y consumir agua potable. No tener contacto con sangre o fluidos de otras personas",
        "consideraciones": "..."
    },
    {
        "nombre": "Celulitis",
        "descripcion": "Infección cutánea bacteriana común y potencialmente grave.",
        "sintomas": [["Erupciones rojas",0.15],["Calor",0.09],["Ampolla",0.09],["Escalofrios",0.09],["Fiebre",0.08],["Malestar general",0.07],["Pus",0.15]],
        "causas": "Factores hormonales juegan un papel importante en la apariencia de celulitis, así como la genética y el peso.",
        "recomendaciones": "Llevar una dieta equilibrada, pobre en grasas e hidratos de carbono y rica en verduras y frutas. Beber de uno a dos litros de aguda diarios. Moderar el consumo de café y alcohol.",
        "consideraciones": "..."
    },
    {
        "nombre": "Obesidad",
        "descripcion": "Trastorno caracterizado por niveles excesivos de grasa corporal que aumentan el riesgo de tener problemas de salud.",
        "sintomas": [["Grasa corporal excesiva",0.12],["Dolor en articulaciones",0.15],["Apetito desenfrenado",0.09],["Fatiga",0.05],["Dolor en las piernas",0.14],["Pérdida de control para orinar",0.13],["Dificultad para respirar",0.12]],
        "causas": "Aumento en la ingesta de alimentos de alto contenido calórico que son ricos en grasa y ademas, un descenso en la actividad física",
        "recomendaciones": "Establecer un horario regular de comidas y evitar comer fuera de los tiempos de comida u omitir alguna comida",
        "consideraciones": "..."
    },
    {
        "nombre": "Hipertension Arterial",
        "descripcion": "Afección en la que la presión de la sangre hacia las paredes de la arteria es demasiado alta.",
        "sintomas": [["Vómitos",0.08],["Confusión",0.07],["Náuseas",0.08],["Dolor de cabeza",0.16],["Dificultad para respirar",0.10],["Sangrado nasal",0.12]],
        "causas": "Suele ser hereditaria. Sobrepeso u obesidad es otra causa.",
        "recomendaciones": "Reducir el exceso de peso, reducir el consumo de sodio, hacer ejercicio regularmente, dejar de fumar y limitar la cantidad de alcohol que bebes.",
        "consideraciones": "..."
    },
    {
        "nombre": "Vaginitis",
        "descripcion": "La vaginitis es una inflamación de la vagina que puede dar como resultado secreción, picazón y dolor.",
        "sintomas": [["Cambio de color del flujo vaginal",0.15],["Irritación vaginal",0.13],["Micción dolorosa",0.12],["Dolor durante las relaciones sexuales",0.10],["Cambio de olor en el flujo vaginal",0.07]],
        "causas": "La causa es un cambio en el equilibrio de las bacterias vaginales o una infección. La reducción de los niveles de estrógeno después de la menopausia y algunos trastornos de la piel también pueden causar vaginitis.",
        "recomendaciones": "Una buena higiene puede ayudar a prevenir la reaparición de algunos tipos de vaginitis, así como a aliviar algunos síntomas",
        "consideraciones": "Las mujeres con vaginosis bacteriana o tricomoniasis corren un mayor riesgo de contraer infecciones de trasmisión sexual debido a la inflamación que causan dichas enfermedades."
    },
    {
        "nombre": "Virus del Zika",
        "descripcion": "El virus del Zika es una infección viral que se transmite principalmente por picaduras de mosquitos, que ocurre sobre todo en áreas tropicales y subtropicales del mundo.",
        "sintomas": [["Fiebre leve",0.02],["Sarpullido",0.02],["Dolor en las articulaciones",0.03],["Conjuntivitis",0.07],["Dolor de cabeza",0.01],["Dolor muscular",0.01]],
        "causas": "El virus del Zika es causado con mayor frecuencia por un virus que se transmite por la picadura de un mosquito infectado. Los mosquitos que transmiten el virus pertenecen a dos especies de Aedes que se encuentran en todo el mundo.",
        "recomendaciones": "Mantener relaciones sexuales seguras,Permanece en ambientes con aire acondicionado o bien protegidos con mosquiteros, Usa repelente de insectos.",
        "consideraciones": "Las mujeres infectadas con el virus del Zika durante el embarazo tienen un mayor riesgo de aborto espontáneo, parto prematuro y muerte fetal intraútero."
    },
    {
        "nombre": "Virus del Nilo Occidental",
        "descripcion": "Esta enfermedad es una flavivirosis de origen africano subsahariano que produce encefalitis en equinos y también humanos, pudiendo afectar también a las aves, quienes actúan como su reservorio natural.",
        "sintomas": [["Temblores musculares",0.15],["Convulsiones",0.12],["Entumecimiento",0.08],["Confusión",0.08],["Rigidez en el cuello",0.09],["Fiebre alta",0.10]],
        "causas": "Por lo general, el virus del Nilo Occidental se transmite a los humanos y animales a través de las picaduras de mosquitos infectados. Los mosquitos se contagian y son portadores del virus después de picar a pájaros infectados. No te contagiarás por el contacto casual con una persona o animal infectados.",
        "recomendaciones": "La mejor opción para prevenir el virus del Nilo Occidental y otras enfermedades trasmitidas por mosquitos es evitar exponerte a esos insectos y eliminar el agua estancada",
        "consideraciones": "..."
    },
    {
        "nombre": "Varicela",
        "descripcion": "La varicela es una enfermedad viral que se caracteriza por la aparición en la piel de varios brotes de lesiones típicas, formadas por pequeñas pápulas que se transforman en vesículas (con contenido líquido) y que al secarse forman costras.",
        "sintomas": [["Exantema",0.20],["Costras",0.09],["Fiebre",0.04],["Picor intenso",0.06],["Vesículas claras con una base rojiza",0.16]],
        "causas": "El responsable es el virus de la varicela zoster, un virus de la familia de los herpes virus. El primer contacto con este virus causa la varicela, dejando inmunidad de por vida.",
        "recomendaciones": "La prevención de la varicela se realiza mediante el uso de inmunoglobulina específica contra el virus de la varicela zóster dentro de las primeras 72 horas post-exposición",
        "consideraciones": "En la mayoría de los casos aparece en niños menores de 10 años, siendo una enfermedad altamente contagiosa."
    },
    {
        "nombre": "Vitiligo",
        "descripcion": "El vitiligo es una enfermedad que causa la pérdida de color de la piel en manchas. Las áreas descoloridas generalmente se agrandan con el tiempo. La afección puede afectar la piel de cualquier parte del cuerpo.",
        "sintomas": [["Pérdida del color de la piel",0.20],["Coloración blanca",0.20],["Pérdida de color en los tejidos que recubren el interior de la boca",0.20]],
        "causas": "El vitíligo se presenta cuando las células que producen el pigmento (melanocitos) mueren o suspenden la producción de melanina, el pigmento que le proporciona color a la piel, el cabello y los ojos.",
        "recomendaciones": "Realizar un buen cuidado diario de la piel. Uso de filtro solar para proteger las zonas afectadas más sensibles a la luz solar, y para evitar que las regiones próximas se bronceen, resaltando más el problema.",
        "consideraciones": "..."
    },
    {
        "nombre": "Cervicitis",
        "descripcion": "La cervicitis es una inflamación del cuello del útero, el extremo inferior y estrecho del útero que termina en la vagina.",
        "sintomas": [["Grandes cantidades de un flujo vaginal",0.16],["Micciones frecuentes",0.10],["Dolor durante las relaciones sexuales",0.09],["Sangrado entre períodos menstruales",0.09]],
        "causas": "Las posibles causas de la cervicitis son: Infecciones de transmisión sexual, Reacciones alérgicas y Crecimiento excesivo de bacterias",
        "recomendaciones": "Evitar los irritantes como las duchas vaginales y los tampones con desodorante.",
        "consideraciones": "..."
    },
    {
        "nombre": "Cirrosis",
        "descripcion": "La cirrosis es una etapa tardía de la cicatrización (fibrosis) del hígado producto de muchas formas de enfermedades hepáticas, como la hepatitis y el alcoholismo crónico.",
        "sintomas": [["Fatiga",0.03],["Pérdida de apetito",0.02],["Náuseas",0.02],["Hinchazón de las piernas",0.09],["Aparición de hemorragias",0.10],["Decoloración amarilla en la piel",0.09],["Picazón",0.03]],
        "causas": "Abuso crónico de alcohol, Hepatitis viral crónica, Acumulación de grasas en el hígado, Acumulación de hierro en el cuerpo, Fibrosis quística, Desorden digestivo genético, etc",
        "recomendaciones": "Consuma grandes cantidades de alimentos con carbohidratos, Tome suplementos vitamínicos, en especial vitaminas del complejo B, Consuma una ingesta moderada de grasas.",
        "consideraciones": "..."
    },
    {
        "nombre": "Sarcoma de Ewing",
        "descripcion": "El sarcoma de Ewing es un tipo raro de cáncer que se produce en los huesos o en el tejido blando alrededor de los huesos.",
        "sintomas": [["Sensibilidad cerca del área afectada",0.10],["Dolor de huesos",0.11],["Cansancio",0.05],["Fiebre",0.02],["Pérdida de peso",0.03],["Hinchazón cerca del área afectada",0.10],["Dolor cerca del área afectada",0.10]],
        "causas": "No está claro qué causa el sarcoma de Ewing.",
        "recomendaciones": "Realizar quimioterapia lo más antes posible",
        "consideraciones": "En ciertas situaciones se podrían utilizar otros tratamientos, incluida la radioterapia."
    },
    {
        "nombre": "Síndrome de Down",
        "descripcion": "El síndrome de Down es un trastorno genético que se origina cuando la división celular anormal produce una copia adicional total o parcial del cromosoma 21. Este material genético adicional provoca los cambios en el desarrollo y en las características físicas relacionados con el síndrome de Down.",
        "sintomas": [["Rostro aplanado",0.15],["Cabeza pequeña",0.07],["Cuello corto",0.08],["Lengua protuberante",0.09],["Poco tono muscular",0.09],["Flexibilidad excesiva",0.14],["Baja estatura",0.14]],
        "causas": "El síndrome de Down se genera cuando se produce una división celular anormal en el cromosoma 21. Estas anomalías en la división celular provocan una copia adicional parcial o total del cromosoma 21. Este material genético adicional es responsable de los rasgos característicos y de los problemas de desarrollo del síndrome de Down.",
        "recomendaciones": "Si tienes un riesgo elevado de tener un niño con síndrome de Down o ya tienes un niño con síndrome de Down, quizá desees consultar con un asesor en genética antes de quedar embarazada.",
        "consideraciones": "La mayoría de las veces, el síndrome de Down no es hereditario. Se produce por un error en la división celular en las primeras etapas del desarrollo del feto."
    },
    {
        "nombre": "Sarcoma pleomórfico indiferenciado",
        "descripcion": "El sarcoma pleomórfico indiferenciado es un tipo de cáncer poco común que comienza principalmente en los tejidos blandos del cuerpo. Los tejidos blandos conectan, sostienen y recubren otras estructuras del cuerpo",
        "sintomas": [["Un bulto creciente",0.20],["Entumecimiento",0.07],["Hinchazón en la mano",0.10],["Pérdida de apetito",0.05],["Fiebre",0.03],["Pérdida de peso",0.02]],
        "causas": "No se sabe con exactitud qué causa el sarcoma pleomórfico indiferenciado.",
        "recomendaciones": "Se podrían recomendar otros tratamientos, como la radioterapia y quimioterapia, antes de la cirugía, para reducir el tamaño del cáncer y que sea más fácil de extirpar sin amputar el miembro afectado.",
        "consideraciones": "..."
    },
    {
        "nombre": "Leucemia",
        "descripcion": "La leucemia es el cáncer de los tejidos que forman la sangre en el organismo, incluso la médula ósea y el sistema linfático.",
        "sintomas": [["Fatiga",0.08],["Pérdida de peso",0.03],["Ganglios linfáticos inflamados",0.09],["Formación de hematomas",0.10],["Sangrado nasal",0.2],["Manchas rojas en la piel",0.9],["Hiperhidrosis",0.10]],
        "causas": "Los científicos no entienden las causas exactas de la leucemia. Parece desarrollarse a partir de una combinación de factores genéticos y ambientales.",
        "recomendaciones": "Se recomienda comer alimentos saludables todos los días y no fumar",
        "consideraciones": "..."
    },
    {
        "nombre": "Dengue",
        "descripcion": "El dengue es una enfermedad transmitida por mosquitos, y ocurre en zonas tropicales y subtropicales del mundo. El dengue leve puede ocasionar fiebre alta y síntomas similares a la gripe.",
        "sintomas": [["Dolor de cabeza", 0.02],["Dolor muscular",0.03],["Náuseas",0.04],["Vómitos",0.04],["Dolor detrás de los ojos",0.10],["Glándulas inflamadas",0.08],["Erupción",0.02]],
        "causas": "La fiebre del dengue es causada por cualquiera de los cuatro virus del dengue. No se puede contraer la fiebre del dengue por estar cerca de una persona infectada. En cambio, la fiebre del dengue se transmite a través de las picaduras de mosquitos.",
        "recomendaciones": "Se recomienda vacunarse y evitar las picaduras de mosquitos",
        "consideraciones": "En las zonas del mundo donde el dengue es frecuente, se aprueba una vacuna contra el dengue (Dengvaxia) para las personas de entre 9 y 45 años que ya lo tuvieron al menos una vez. La vacuna se administra en tres dosis en el curso de 12 meses."
    },
    {
        "nombre": "Neumonía",
        "descripcion": "La neumonía es una infección que inflama los sacos aéreos de uno o ambos pulmones. Los sacos aéreos se pueden llenar de líquido o pus (material purulento), lo que provoca tos con flema o pus, fiebre, escalofríos y dificultad para respirar.",
        "sintomas": [["Dolor en el pecho al respirar",0.14],["Desorientación",0.07],["Tos con flema",0.13],["Fatiga",0.01],["Baja temperatura corporal",0.13],["Dificultad para respirar",0.13],["Escalofríos",0.13]],
        "causas": "Muchos gérmenes pueden causar neumonía. Los más comunes son las bacterias y los virus en el aire que respiramos. El cuerpo normalmente evita que estos gérmenes infecten los pulmones. Pero a veces estos gérmenes pueden dominar tu sistema inmunitario, incluso si tu salud es generalmente buena.",
        "recomendaciones": "Se recomienda aplicarse la vacuna antineumocócica, la vacuna contra la influenza, dejar de fumar, reducir el consumo de alcohol, etc. ",
        "consideraciones": "..."
    },
    {
        "nombre": "Neuralgia del trigémino",
        "descripcion": "La neuralgia del trigémino es una afección que provoca sensaciones dolorosas similares a una descarga eléctrica en un lado de la cara. Esta afección de dolor crónico afecta el nervio trigémino, que trasmite las sensaciones de la cara al cerebro",
        "sintomas": [["Dolor que se presenta con espasmos faciales",0.18],["Dolor que afecta un solo lado del rostro a la vez",0.20],["Dolor en las zonas inervadas por el nervio trigémino",0.25],["Ataques espontáneos de dolor",0.10]],
        "causas": "El problema suele ser el contacto entre un vaso sanguíneo normal (en este caso, una arteria o una vena) y el nervio trigémino ubicado en la base del cerebro. Este contacto ejerce presión sobre el nervio y provoca un mal funcionamiento de este.",
        "recomendaciones": "Se recomienda entonces evitar los alimentos picantes, ácidos y con cafeína",
        "consideraciones": "..."
    },
    {
        "nombre": "Úlcera péptica",
        "descripcion": "Las úlceras pépticas son llagas abiertas que aparecen en el revestimiento interno del estómago y la parte superior del intestino delgado.",
        "sintomas": [["Dolor de estómago",0.15],["Intolerancia a los alimentos grasos",0.14],["Náuseas",0.06],["Acidez estomacal",0.05],["Sensación de plenitud",0.08]],
        "causas": "Las úlceras pépticas se presentan cuando el ácido del aparato digestivo corroe la superficie interior del estómago y del intestino delgado. El ácido puede crear una llaga abierta que duele y puede sangrar.",
        "recomendaciones": "Modera el consumo de café y de comidas picantes, No abuses de aspirinas y antinflamatorios no esteroideos, No te excedas en el uso de protectores de estómago, etc.",
        "consideraciones": "..."
    },
    {
        "nombre": "Gastritis",
        "descripcion": "La gastritis es un término general para un grupo de enfermedades con un punto en común: la inflamación del revestimiento del estómago.",
        "sintomas": [["Malestar en el abdomen",0.20],["Ardor en el abdomen",0.15],["Náuseas",0.4],["Vómitos",0.4]],
        "causas": "La gastritis es una inflamación del revestimiento del estómago. La debilidad o una lesión de la barrera mucosa que protege la pared del estómago permite que los jugos digestivos dañen e inflamen el revestimiento del estómago.",
        "recomendaciones": "Evitar bebidas estimulantes: café, té y bebidas carbonatadas. Evitar el alcohol y el tabaco. Evitar alimentos grasos y picantes. Consumir frutas y verduras preferiblemente cocidas, evitando su ingestión en crudo.",
        "consideraciones": "..."
    },
    {
        "nombre": "Endometriosis",
        "descripcion": "La endometriosis es un trastorno a menudo doloroso en el cual el tejido similar al tejido que normalmente recubre el interior del útero (el endometrio) crece fuera del útero. La endometriosis afecta más comúnmente a los ovarios, las trompas de Falopio y el tejido que recubre la pelvis.",
        "sintomas": [["Períodos dolorosos",0.15],["Dolor al tener relaciones sexuales",0.06],["Dolor al orinar",0.10],["Sangrado excesivo",0.04],["Infertilidad",0.20],["Dolor al defecar",0.10]],
        "causas": "Aunque la causa exacta de la endometriosis no es clara, las posibles explicaciones incluyen las siguientes: Menstruación retrógrada. En la menstruación retrógrada, la sangre menstrual que contiene células endometriales regresa a través de las trompas de Falopio hacia la cavidad pélvica en lugar de salir del cuerpo.",
        "recomendaciones": "Se recomienda reducir el consumo de alimentos enlatados (conservas de pescado, legumbres, verduras) potenciando el uso y la compra de tarros de cristal",
        "consideraciones": "..."
    },
    {
        "nombre": "Anemia",
        "descripcion": "La anemia es una afección en la cual careces de suficientes glóbulos rojos sanos para transportar un nivel adecuado de oxígeno a los tejidos del cuerpo. La anemia, también conocida como nivel bajo de hemoglobina, puede hacer que te sientas cansado y débil.",
        "sintomas": [["Fatiga",0.10],["Debilidad",0.07],["Piel pálida",0.08],["Latidos del corazón irregulares",0.10],["Mareos",0.09],["Dolor en el pecho",0.04],["Dolor de cabeza",0.02]],
        "causas": "La anemia puede deberse a una afección presente al nacer (congénita) o a una afección que se desarrolla (adquirida). La anemia se produce cuando la sangre no tiene suficientes glóbulos rojos.",
        "recomendaciones": "Se recomienda consumir mínimo dos porciones al día de carnes rojas, pollo o pescado",
        "consideraciones": "..."
    },
    {
        "nombre": "Tuberculosis",
        "descripcion": "La tuberculosis es una enfermedad infecciosa y potencialmente seria que afecta principalmente los pulmones. La bacteria que causa la tuberculosis se contagia de persona a persona a través de pequeñas gotitas diseminadas en el aire al toser o estornudar.",
        "sintomas": [["Tos con sangre",0.15],["Dolor en el pecho",0.09],["Escalofríos",0.06],["Dolor al respirar",0.08],["Sudoraciones nocturnas",0.12],["Fiebre",0.01]],
        "causas": "La tuberculosis es causada por bacterias que se contagian de persona a persona a través de gotitas microscópicas diseminadas en el aire. Esto puede suceder cuando una persona con la forma activa de la tuberculosis no tratada tose, habla, estornuda, escupe, se ríe, o canta.",
        "recomendaciones": "Se recomienda el cumplimiento de la quimioprofilaxis de las personas infectadas.",
        "consideraciones": "..."
    },
    {
        "nombre": "Ébola",
        "descripcion": "El Ébola es una enfermedad potencialmente letal provocada por el virus del mismo nombre, y es una de las más mortíferas que se conocen para el ser humano.",
        "sintomas": [["Escalofríos",0.04],["Dolor de garganta",0.06],["Dolor muscular",0.06],["Debilidad",0.06],["Fatiga",0.08],["Erupción cutánea",0.10],["Fiebre muy elevada",0.20]],
        "causas": "El virus del Ebola se introduce en la población humana por contacto estrecho con órganos, sangre, secreciones u otros líquidos corporales de animales infectados, de chimpancés, gorilas, murciélagos frugívoros, monos, antílopes y puercoespines infectados que se habían encontrado muertos o enfermos en la selva.",
        "recomendaciones": "Se recomienda lavarse las manos con frecuencia y evitar las carnes de animales salvajes.",
        "consideraciones": "No existe un tratamiento específico contra el virus y hasta hace poco tampoco había vacuna. El tratamiento estándar se centra en tratar los síntomas para aliviar el sufrimiento de los pacientes e intentar reducir la mortalidad."
    },
    {
        "nombre": "Papera",
        "descripcion": "Las paperas son una infección viral que afecta principalmente a las glándulas salivales que se encuentran cerca de los oídos. Las paperas pueden provocar inflamación de una de las glándulas o ambas.",
        "sintomas": [["Dolor en las glándulas salivales",0.2],["Dolor al masticar",0.1],["Fiebre",0.1],["Dolor de cabeza",0.1],["Debilidad",0.05]],
        "causas": "La parotiditis es causada por un virus que se disemina fácilmente de una persona a otra a través de la saliva infectada.",
        "recomendaciones": "Se recomiensa utilizar una compresa caliente o fría para aliviar el dolor de las glándulas inflamadas",
        "consideraciones": "..."
    },
    {
        "nombre": "Tétanos",
        "descripcion": "Enfermedad grave del sistema nervioso comúnmente conocida como 'trismo' que es causada por una bacteria productora de toxinas.",
        "sintomas": [["Espasmos musculares",0.2],["Rigidez muscular",0.2],["Tensión muscular",0.2],["Espasmos dolorosos",0.2], ["Dificultad para tragar",0.05],["Fiebre",0.05]],
        "causas": "La bacteria que causa el tétanos se llama Clostridium tetani, esta bacteria puede sobrevivir en la tierra y en las heces pero se vuelve activa cuando entran en una herida. A medida que crecen y se dividen, liberan la toxina tetanospasmina que afecta los nervios del cuerpo que controlan los músculos.",
        "recomendaciones": "El tétanos se puede prevenir con una vacuna. En el caso de niños se aplica como parte de las vacunas de refuerzo.",
        "consideraciones": "El tétanos es una enfermedad que pone en riesgo la vida. Busca atención de emergencia si tienes signos o síntomas de tétanos y no te has vacunado."
    },
    {
        "nombre": "Asma",
        "descripcion": "Afección en la que las vías respiratorias se estrechan e hinchan, lo que puede producir mayor mucosidad. Esto puede dificultar la respiración y provocar tos, un silbido (sibilancia) al exhalar y falta de aire.",
        "sintomas": [["Falta de aire",0.5],["Dolor de pecho",0.2],["Sibilancia",0.2],["Problemas para dormir",0.02],["Tos",0.05]],
        "causas": "No está claro por qué algunas personas contraen asma y otras no; sin embargo, es probable que se deba a una combinación de factores ambientales y/o genéticos",
        "recomendaciones": "El asma no tiene cura, pero sus síntomas pueden controlarse. Dado que el asma suele cambiar con el tiempo, es importante que colabores con el médico para hacer un seguimiento de los signos y los síntomas y ajustar el tratamiento según sea necesario.",
        "consideraciones": "Los ataques de asma graves pueden poner en riesgo la vida. Debes acudir al médico con urgencia cuando haya falta de mejora o empeoramiento, incluso después de usar un inhalador"
    },
    {
        "nombre":"Esclerosis",
        "descripcion":"Enfermedad en la que el sistema inmunológico degrada la cubierta protectora de los nervios.",
        "sintomas": [["Perdida de visión",0.15],["Dolor",0.05],["Fatiga",0.05],["Disminución de Coordinación",0.1],["Dificultad para caminar",0.05],["Calambres",0.05],["Debilidad",0.05],["Espasmos",0.05]],
        "causas": "No se sabe exactamente qué causa la EM. La creencia más frecuente es que es causada por virus, un defecto genético o ambos. Los factores ambientales también pueden influir. Usted es ligeramente más propenso a presentar esta enfermedad si tiene antecedentes familiares de EM o si vive en una parte del mundo donde esta enfermedad es más común.",
        "recomendaciones": "La fisioterapia y los medicamentos que inhiben el sistema inmunológico pueden aliviar los síntomas y reducir la velocidad de la progresión de la enfermedad.",
        "consideraciones": "Algunas personas pueden no presentar síntomas durante gran parte de sus vidas, mientras que otras pueden tener graves síntomas crónicos que nunca desaparecen."
    },
    {
        "nombre":"Fibromialgia",
        "descripcion":"Dolor y sensibilidad muscular generalizados.",
        "sintomas": [["Dolor Muscular",0.15],["Sensibilidad",0.15],["Malestar",0.01],["Fatiga",0.02],["Estreñimiento",0.02],["Espasmos",0.05],["Nerviosismo",0.01],["Olvido",0.01]],
        "causas": "No se conoce la causa de esta alteración, pero se piensa que hay muchos factores implicados. Hay personas que desarrollan la enfermedad sin causa aparente y en otras comienza después de procesos identificables como puede ser una infección bacteriana o viral, un accidente de automóvil o en otros casos aparece después de que otra enfermedad conocida limite la calidad de vida.",
        "recomendaciones": "La enfermedad no tiene curación definitiva. El objetivo del tratamiento es mejorar el dolor y tratar los síntomas acompañantes, para conseguir una gran mejoría en la calidad de vida de estos pacientes. Es importante conocer la naturaleza de la enfermedad y cuales son los factores desencadenantes de brotes, realizar tratamiento de las alteraciones psicológicas asociadas si las hay (ansiedad y depresión) y ejercicio físico suave diariamente.",
        "consideraciones": "A pesar de tener un carácter benigno porque no produce secuelas físicas (no destruye las articulaciones, no ocasiona lesiones irreversibles ni deformidades) ni influye en la supervivencia del paciente, el impacto que origina en la calidad de vida de quien la padece es muy variable de unas personas a otras pudiendo ser limitante."
    },
    {
        "nombre":"Salmonella",
        "descripcion": "La salmonela es más común entre los niños. Las personas con sistemas inmunológicos comprometidos, como los adultos de edad avanzada, los bebés y las personas con SIDA, suelen presentar los casos más graves.",
        "sintomas": [["Diarrea",0.15],["Fiebre",0.1],["Escalosfríos",0.15],["Dolor Abdominal",0.1],["Deshidratación",0.05],["Fatiga",0.05],["Dolor Muscular",0.03],["Dolor de Cabeza",0.02]],
        "causas": "Infección provocada por la bacteria de la salmonela, usualmente ocasionada por la ingesta de alimentos o agua contaminados.",
        "recomendaciones": "El tratamiento consiste en fluidos. La mayoría de las personas solamente necesitan líquidos para recuperarse en menos de una semana. Las infecciones graves pueden requerir cuidado médico, incluida la administración de líquidos por vía intravenosa y, en algunos casos, antibióticos.",
        "consideraciones": "Puede sanar solo. La afección generalmente mejora con el tiempo sin tratamiento."
    },
    {
        "nombre": "Soriasis",
        "descripcion": "Afección en la que las células de la piel se acumulan para formar escamas y manchas secas que producen comezón.",
        "sintomas": [["Sarpullido",0.2],["Erupciones",0.05],["Descamación",0.05],["Enrojecimiento",0.05],["Fisuras",0.05],["Piel escamosa",0.05],["Picazón",0.15],["Tendones inflamados",0.05]],
        "causas": "Se cree que la psoriasis es un problema del sistema inmunitario que hace que las células de la piel crezcan a un ritmo más rápido de lo normal. En el tipo más frecuente de psoriasis, conocido como psoriasis de placas, esta rápida renovación de las células da lugar a manchas escamosas y secas.",
        "recomendaciones": "Control del estrés, Vaselina, Fototerapia, Terapia con luz ultravioleta, Emoliente, Urea y Alquitrán de hulla",
        "consideraciones": "La afección no es contagiosa."
    },
    {
        "nombre": "Tendinitis",
        "descripcion": "Afección en la que se inflama el tejido que conecta el músculo con el hueso.",
        "sintomas": [["Dolor",0.1],["Sensibilidad",0.1],["Enrojecimiento",0.01],["Hinchazon",0.05],["Calor",0.05],["Rigidez",0.1],["Inflamación",0.04],["Debilidad",0.01]],
        "causas": "Aunque la tendinitis puede ser causada por una lesión repentina, es mucho más probable que la enfermedad se origine en la repetición de un movimiento en particular a lo largo del tiempo. Muchas personas padecen tendinitis porque sus trabajos o pasatiempos implican movimientos repetitivos, que tensionan los tendones.",
        "recomendaciones": "La mayoría de los casos de tendinitis se pueden tratar eficazmente con reposo, fisioterapia y medicamentos para reducir el dolor. En caso de que la tendinitis sea grave y ocasione la rotura de un tendón, probablemente necesites una cirugía.",
        "consideraciones":"Sin el tratamiento correcto, la tendinitis puede incrementar el riesgo de sufrir rotura del tendón, una afección mucho más grave que tal vez requiera cirugía. En caso de que la irritación del tendón persista durante varias semanas o meses, se puede manifestar una enfermedad conocida como «tendinosis». Esta enfermedad consiste en cambios degenerativos en el tendón, junto con un crecimiento anormal de nuevos vasos sanguíneos." 
    },
    {
        "nombre": "Asperger",
        "descripcion": "Trastorno del comportamiento que afecta la capacidad de socializar y comunicarse con efectividad.",
        "sintomas": [["Agresión",0.1],["Aislamiento",0.15],["Nervios",0.05],["Impulsividad",0.1],["Coordinación Deficiente",0.05],["Ansiedad",0.05],["Enfado",0.05],["Temor",0.05]],
        "causas": "Se desconoce la causa exacta, pero el síndrome de Asperger puede deberse a una combinación de factores genéticos y ambientales que provocan cambios en el desarrollo del cerebro.",
        "recomendaciones": "La terapia conductual y de formación en la comunicación permite a los pacientes con trastornos del aprendizaje socializar mejor.",
        "consideraciones": "El síndrome de Asperger es un trastorno del espectro autista que suele ser menos grave."
    },
    {
        "nombre": "Preeclampsia",
        "descripcion": "Complicación del embarazo potencialmente severa caracterizada por una presión arterial elevada.",
        "sintomas": [["Hipertensión",0.1],["Hinchazón",0.1],["Retención de Líquidos",0.1],["Presión Alta",0.05],["Náuseas",0.05],["Visión Borrosa",0.01],["Fatiga",0.06],["Aumento de Peso",0.01]],
        "causas": "La causa exacta de la preeclampsia posiblemente implique varios factores. Los especialistas creen que comienza en la placenta, el órgano que nutre al feto durante el embarazo. En las primeras semanas del embarazo, se forman nuevos vasos sanguíneos y estos evolucionan para suministrar oxígeno y nutrientes a la placenta.",
        "recomendaciones": "Usualmente, la preeclampsia se puede controlar con medicamentos orales o intravenosos hasta que el bebé madura lo suficiente como para nacer. A menudo, implica ponderar los riesgos de un nacimiento prematuro y los riesgos de continuar con los síntomas de la preeclampsia.",
        "consideraciones": "Si bien es poco frecuente, la preeclampsia también se puede presentar en una mujer después de dar a luz a su bebé, casi siempre dentro de las siguientes 48 horas. Esto se denomina preeclampsia posparto."
    },
    {
        "nombre": "Apendicitis",
        "descripcion": "Afección dolorosa en la que el apéndice se inflama y se llena de pus.",
        "sintomas": [["Dolor Abdominal",0.15],["Náuseas",0.02],["Vómitos",0.03],["Pérdida del apetito",0.03],["Fiebre",0.02],["Escalosfríos",0.02],["Diarrea",0.01],["Malestar",0.09]],
        "causas": "La causa probable de la apendicitis es una obstrucción en el recubrimiento del apéndice que da como resultado una infección. Las bacterias se multiplican rápidamente y hacen que el apéndice se inflame, se hinche y se llene de pus. Si no se trata inmediatamente, el apéndice puede romperse.",
        "recomendaciones": "El tratamiento más común para la apendicitis es la extirpación quirúrgica del apéndice.",
        "consideraciones": "La apendicitis puede ser difícil de diagnosticar porque existen otras condiciones que causan síntomas similares. No todos los que tienen apendicitis exhiben todos estos síntomas. Si usted tiene cualquiera de estos síntomas, particularmente dolor abdominal que continúa y empeora, contacte inmediatamente a su médico."
    },
    {
        "nombre": "Hepatitis C",
        "descripcion": "La hepatitis C al igual que el tipo B, puede conducir a complicaciones de salud graves , como cirrosis, insuficiencia hepática y cáncer de hígado. Puede ser aguda o crónica, sin embargo, la mayoría de las personas con hepatitis C aguda, terminan padeciendo la crónica.",
        "sintomas": [["Coloración Amarillenta",0.2],["Pérdida de apetito",0.1],["Fiebre",0.01],["Heces Claras",0.05],["Orina Oscura",0.05],["Dolor Estomacal",0.1],["Vómitos",0.01],["Dolor de articulaciones",0.15]],
        "causas": "La hepatitis C es una enfermedad infecciosa, ocasionada por el virus VHC, del cual existen siete genotipos distintos. Existen diversas vías y factores de riesgo para contraer la enfermedad. Estas incluyen: Consumir drogas inyectadas (transmisión a través de una aguja infectada). Haberse realizado perforaciones o tatuajes bajo condiciones de higiene dudosas.",
        "recomendaciones": "Si la afección es aguda, no existe un tratamiento específico. En la mayoría de los casos, el tratamiento consiste en la administración de medicamentos antivirales. Cuando la hepatitis se hace crónica, lo más probable es que sea necesario un trasplante de hígado debido a las complicaciones derivadas de la enfermedad.",
        "consideraciones": "No existe una vacuna para el virus de la hepatitis C."
    },
    {
        "nombre": "Hepatitis D",
        "descripcion": "La hepatitis D, es un virus que molecularmente está formado por una cadena de ARN y su manifestación requiere que la persona haya estado infectada previamente con el virus de la hepatitis B.",
        "sintomas": [["Color amarillento de los ojos",0.20],["Dolor abdominal",0.07],["Orina oscura",0.10],["Fatiga",0.06],["Picazón",0.04],["Pérdida del apetito",0.08],["Color amarillento en la piel",0.20]],
        "causas": "La causa más probable de padecer hepatitis D, es el contagio de una persona infectada a una que no está pero que si padece de hepatitis tipo B, sin embargo, existen otros factores de riesgo que favorecen el contagio. Uno de ellos, es no estar vacunado contra la hepatitis B. También son factores de riesgo el uso de drogas por vía intravenosa y tener relaciones sexuales sin la debida protección.",
        "recomendaciones": "Se aconseja evitar el consumo de alcohol, tener una alimentación lo más saludable y balanceada posible y guardar reposo, al menos hasta que el color amarillento de los ojos y la piel haya desaparecido. Sin embargo, estas últimas prescripciones no tienen fundamento científico.",
        "consideraciones": "Los síntomas de la hepatitis D, no difieren de los síntomas padecidos en otros tipos de infección de hepatitis. Por esta razón, al estar padeciendo hepatitis B crónica, generalmente se indica una prueba de descarte de VHD, aunque este tipo de pruebas de diagnóstico no están normalizadas y su disponibilidad es limitada."
    },
    {
        "nombre": "Hepatitis E",
        "descripcion": "Este tipo de hepatitis, está presente en todas las partes del mundo, pero presenta una mayor prevalencia en los países asiáticos. Es causada por el virus VHE.",
        "sintomas": [["Fiebre",0.05],["Pérdida del apetito",0.05],["Prurito",0.2],["Ictericia",0.2],["Aumento del tamaño del hígado",0.2]],
        "causas": "La mayor causa de contagio de la hepatitis E es por medio de la transmisión fecal-oral, es decir, a través de la ingesta de alimentos manipulados en condiciones de higiene deficiente y el consumo de agua contaminada, siendo esta última una de las vías de contagio más comunes. Comer carnes crudas o semicrudas y la transmisión de la madre al feto, también son vías de contacto. Esta infección es especialmente peligrosa en mujeres embarazadas, quienes corren el riesgo de sufrir insuficiencia hepática aguda, con riesgo de muerte tanto para ellas como para sus fetos.",
        "recomendaciones": "No existe un tratamiento específico para la hepatitis E, por lo general suele remitir de manera espontánea y no es necesaria la hospitalización y debe evitarse la automedicación. Es recomendado el reposo, buena nutrición, evitar el consumo de bebidas alcohólicas y el uso de medicamentos no prescritos.",
        "consideraciones": "No todos los pacientes con hepatitis E padecen síntomas. Si aparecen son muy similares a los síntomas detectados en otras infecciones por hepatitis."
    },
    {
        "nombre": "Hígado graso",
        "descripcion": "Acumulación excesiva de grasa en el hígado.",
        "sintomas": [["Fatiga",0.05],["Pérdida de peso",0.01],["Dolor Abdominal",0.05],["Cansancio",0.02]],
        "causas": "La causa más común de hígado graso es el alcoholismo o el consumo excesivo de alcohol. En muchos casos, no se sabe exactamente qué causa el hígado graso en las personas que no beben mucho alcohol.",
        "recomendaciones": "El tratamiento consiste en reducir los factores de riesgo, como la obesidad, mediante la dieta y la actividad física. Generalmente es una afección benigna, pero en una pequeña cantidad de pacientes puede ocasionar insuficiencia hepática (cirrosis).",
        "consideraciones": "Si bien el tratamiento puede ayudar, esta enfermedad no tiene cura."
    },
    {
        "nombre": "Fiebre amarilla",
        "descripcion": "Infección viral que se propaga por una especie determinada de mosquito.",
        "sintomas": [["Fiebre",0.1],["Dolor de Cabeza",0.15],["Náuseas",0.05],["Vómitos",0.04],["Dolor muscular",0.04],["Sensibilidad a la luz",0.18],["Ictericia",0.1],["Disminución de Orina",0.14]],
        "causas": "La fiebre amarilla es causada por un virus propagado por el mosquito Aedes aegypti. Estos mosquitos prosperan en las viviendas humanas y cerca de ellas, donde se reproducen incluso en el agua más limpia. La mayoría de los casos de fiebre amarilla se produce en el África subsahariana y en las zonas tropicales de América del Sur.",
        "recomendaciones": "No existe un tratamiento específico para la fiebre amarilla. El tratamiento es de apoyo y se centra en: Hemoderivados para el sangrado grave. Diálisis para la insuficiencia renal. Líquidos por vía intravenosa (líquidos intravenosos)",
        "consideraciones": "Cualquier persona puede contraer la fiebre amarilla, pero las personas mayores presentan un riesgo mayor de infección grave. Si una persona es picada por un mosquito infectado, los síntomas generalmente se manifiestan entre 3 y 6 días más tarde."
    },
    {
        "nombre": "Gripe porcina",
        "descripcion": "La influenza porcina (gripe porcina) es una enfermedad respiratoria de los cerdos, causada por virus de influenza tipo A que provocan brotes regulares de influenza en los cerdos.",
        "sintomas": [["Fiebre",0.06],["Depresión",0.15],["Secreción nasal",0.12],["Inflamación de los ojos",0.14],["Escalofríos",0.09],["Diarrea",0.07],["Dolor de cuerpo",0.08]],
        "causas": "Alguien con gripe tose o estornuda hacia el aire que otros inhalan, alguien toca una perilla de la puerta, un escritorio, un computadora o mostrador con el virus de la gripe y luego se toca la boca, los ojos o la nariz, alguien toca moco mientras cuida de un niño o un adulto que esté enfermo de gripe, etc.",
        "recomendaciones": "Cubrirse la nariz y boca con papel higiénico al toser o estornudar y luego de su uso tirarlo en un tacho de basura. En caso de no contar con papel se debe cubrir la nariz y boca con el antebrazo. Asimismo, se recomienda lavarse las manos con agua y jabón de manera frecuente.",
        "consideraciones": "..."
    }
]


# {
#     "nombre": "",
#     "descripcion": "",
#     "sintomas": [["",],["",],["",],["",],["",],["",],["",],["",]],
#     "causas": "",
#     "recomendaciones": "",
#     "consideraciones": "..."
# }