export const GET_DIAGNOSIS_REQUEST = 'GET_DIAGNOSIS_REQUEST';
export const GET_DIAGNOSIS_SUCCESS = 'USER_REGISTER_SUCCESS';
export const GET_DIAGNOSIS_FAIL = 'GET_DIAGNOSIS_FAIL';

export const GET_NEAREST_PLACES_REQUEST = 'GET_NEAREST_PLACES_REQUEST';
export const GET_NEAREST_PLACES_SUCCESS = 'GET_NEAREST_PLACES_SUCCESS';
export const GET_NEAREST_PLACES_FAIL = 'GET_NEAREST_PLACES_FAIL';

export const GET_DISEASES_RESULTS_REQUEST = 'GET_DISEASES_RESULTS_REQUEST';
export const GET_DISEASES_RESULTS_SUCCESS = 'GET_DISEASES_RESULTS_SUCCESS';
export const GET_DISEASES_RESULTS_FAIL = 'GET_DISEASES_RESULTS_FAIL';

export const GET_DISEASE_DETAILS_REQUEST = 'GET_DISEASE_DETAILS_REQUEST';
export const GET_DISEASE_DETAILS_SUCCESS = 'GET_DISEASE_DETAILS_SUCCESS';
export const GET_DISEASE_DETAILS_FAIL = 'GET_DISEASE_DETAILS_FAIL';

export const GET_FIRST_AID_DETAILS_REQUEST = 'GET_FIRST_AID_DETAILS_REQUEST';
export const GET_FIRST_AID_DETAILS_SUCCESS = 'GET_FIRST_AID_DETAILS_SUCCESS';
export const GET_FIRST_AID_DETAILS_FAIL = 'GET_FIRST_AID_DETAILS_FAIL';